import type {PropDefinition} from "../../../components/api-reference/ApiReference.tsx";

export const videoPropsData: PropDefinition[] = [
    {
        name: 'src',
        type: 'string',
        description: 'The source URL for the iframe, if rendering an iframe automatically.'
    },
    {
        name: 'title',
        type: 'string',
        defaultValue: "'Video player'",
        description: 'The title for the iframe for accessibility.'
    },
    {
        name: 'aspectRatio',
        type: 'string | number',
        defaultValue: "'16 / 9'",
        description: "The aspect ratio of the video (e.g., '16 / 9', '4 / 3'). Defaults to '16 / 9'."
    },
    {
        name: 'children',
        type: 'ReactNode',
        description: 'Optional children if you want to pass a custom <video>, <embed>, or <object> instead of relying on the default <iframe> generated by the src prop.'
    }
];

export const cssVariables: PropDefinition[] = [
    {
        name: '--lyco-video-ratio',
        type: 'string | number',
        description: 'The aspect ratio applied to the component.'
    }
];

export const apiConfig = [
    {name: 'Video Props', data: videoPropsData},
    {name: 'CSS Variables', data: cssVariables}
];
