import React from 'react';
import './Video.scss';

/**
 * Props for the Video component.
 */
export interface VideoProps extends React.HTMLAttributes<HTMLDivElement> {
    /** The source URL for the iframe, if rendering an iframe automatically. */
    src?: string;
    /** The title for the iframe for accessibility. */
    title?: string;
    /**
     * The aspect ratio of the video (e.g., '16 / 9', '4 / 3').
     * Defaults to '16 / 9'.
     */
    aspectRatio?: string | number;
    /**
     * Optional children if you want to pass a custom <video>, <embed>, or <object>
     * instead of relying on the default <iframe> generated by the src prop.
     */
    children?: React.ReactNode;
}

/**
 * Video component.
 * A UI component for LycoUI.
 */
export const Video = React.forwardRef<HTMLDivElement, VideoProps>(({
                                                                       src,
                                                                       title = 'Video player',
                                                                       aspectRatio = '16 / 9',
                                                                       children,
                                                                       className = '',
                                                                       style,
                                                                       ...rest
                                                                   }, ref) => {
    // Generate the CSS variable for the aspect ratio
    const inlineStyle = {
        '--lyco-video-ratio': aspectRatio,
        ...style
    } as React.CSSProperties;

    return (
        <div
            className={`lyco-video ${className}`}
            style={inlineStyle}
            ref={ref}
            {...rest}
        >
            {src && !children ? (
                <iframe
                    src={src}
                    title={title}
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                    allowFullScreen
                    loading="lazy"
                />
            ) : (
                children
            )}
        </div>
    );
});

Video.displayName = 'Video';
